[platformio]
default_envs = receiver

; --- บอร์ดฝั่งรับ (บนโต๊ะ) ---
[env:receiver]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = +<receiver.cpp>
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5

; --- บอร์ดฝั่งส่ง (ในตู้) ---
[env:sender]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = +<sender.cpp>
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9